export default [
  { "type": "aac", "mime": "audio/aac" },
  { "type": "abw", "mime": "application/x-abiword" },
  { "type": "arc", "mime": "application/x-freearc" },
  { "type": "avi", "mime": "video/x-msvideo" },
  { "type": "azw", "mime": "application/vnd.amazon.ebook" },
  { "type": "bin", "mime": "application/octet-stream" },
  { "type": "bmp", "mime": "image/bmp" },
  { "type": "bz", "mime": "application/x-bzip" },
  { "type": "bz2", "mime": "application/x-bzip2" },
  { "type": "csh", "mime": "application/x-csh" },
  { "type": "css", "mime": "text/css" },
  { "type": "csv", "mime": "text/csv" },
  { "type": "doc", "mime": "application/msword" },
  {
    "type": "docx",
    "mime":
      "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  },
  { "type": "eot", "mime": "application/vnd.ms-fontobject" },
  { "type": "epub", "mime": "application/epub+zip" },
  { "type": "gz", "mime": "application/gzip" },
  { "type": "gif", "mime": "image/gif" },
  { "type": "html", "mime": "text/html" },
  { "type": "ico", "mime": "image/vnd.microsoft.icon" },
  { "type": "ics", "mime": "text/calendar" },
  { "type": "jar", "mime": "application/java-archive" },
  { "type": "jpeg", "mime": ".jpg" },
  { "type": "js", "mime": "text/javascript" },
  { "type": "json", "mime": "application/json" },
  { "type": "jsonld", "mime": "application/ld+json" },
  { "type": "mid", "mime": ".midi" },
  { "type": "mjs", "mime": "text/javascript" },
  { "type": "mp3", "mime": "audio/mpeg" },
  { "type": "mpeg", "mime": "video/mpeg" },
  { "type": "mpkg", "mime": "application/vnd.apple.installer+xml" },
  { "type": "odp", "mime": "application/vnd.oasis.opendocument.presentation" },
  { "type": "ods", "mime": "application/vnd.oasis.opendocument.spreadsheet" },
  { "type": "odt", "mime": "application/vnd.oasis.opendocument.text" },
  { "type": "oga", "mime": "audio/ogg" },
  { "type": "ogv", "mime": "video/ogg" },
  { "type": "ogx", "mime": "application/ogg" },
  { "type": "opus", "mime": "audio/opus" },
  { "type": "otf", "mime": "font/otf" },
  { "type": "png", "mime": "image/png" },
  { "type": "pdf", "mime": "application/pdf" },
  { "type": "php", "mime": "application/x-httpd-php" },
  { "type": "ppt", "mime": "application/vnd.ms-powerpoint" },
  {
    "type": "pptx",
    "mime":
      "application/vnd.openxmlformats-officedocument.presentationml.presentation",
  },
  { "type": "rar", "mime": "application/vnd.rar" },
  { "type": "rtf", "mime": "application/rtf" },
  { "type": "sh", "mime": "application/x-sh" },
  { "type": "svg", "mime": "image/svg+xml" },
  { "type": "swf", "mime": "application/x-shockwave-flash" },
  { "type": "tar", "mime": "application/x-tar" },
  { "type": "tiff", "mime": "image/tiff" },
  { "type": "ts", "mime": "video/mp2t" },
  { "type": "ttf", "mime": "font/ttf" },
  { "type": "txt", "mime": "text/plain" },
  { "type": "vsd", "mime": "application/vnd.visio" },
  { "type": "wav", "mime": "audio/wav" },
  { "type": "weba", "mime": "audio/webm" },
  { "type": "webm", "mime": "video/webm" },
  { "type": "webp", "mime": "image/webp" },
  { "type": "woff", "mime": "font/woff" },
  { "type": "woff2", "mime": "font/woff2" },
  { "type": "xhtml", "mime": "application/xhtml+xml" },
  { "type": "xls", "mime": "application/vnd.ms-excel" },
  {
    "type": "xlsx",
    "mime": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  },
  { "type": "xml", "mime": "XML" },
  { "type": "xul", "mime": "application/vnd.mozilla.xul+xml" },
  { "type": "zip", "mime": "application/zip" },
  { "type": "3gp", "mime": "video/3gpp" },
  { "type": "3g2", "mime": "video/3gpp2" },
  { "type": "7z", "mime": "application/x-7z-compressed" },
];
